### PR TITLE
Handle missing `version` from `package.json`

### PR DESCRIPTION
**Pull request by jtpio**
Trying to use the Draft Changelog workflow on a repo with a `version` in the `package.json`, which is common in monorepos.

See this failing run for reference: https://github.com/jtpio/jupyter_releaser/runs/2933424228

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
Not sure this is enough to handle workspaces, currently seeing another error when testing with this change:

image

But this might actually be something different related to how the packages are retrieved with glob patterns, returning too many results:

 https://github.com/jupyter-server/jupyter_releaser/blob/8285f2d33836d344492f1c08b31f33648edee849/jupyter_releaser/npm.py#L154

**Comment by jtpio** [comment]
> Not sure this is enough to handle workspaces, currently seeing another error when testing with this change:

Will track that in a separate issue.

**Comment by jtpio** [comment]
> Will track that in a separate issue.

Opened https://github.com/jupyter-server/jupyter_releaser/issues/48, so we can go ahead and merge this one as an incremental improvement.

**Pull request merged**
