### PR TITLE
Only run npm pack if there are public packages in workspace

### PR DESCRIPTION
**Pull request by fcollonval**
Fix issue seen in https://github.com/jupyterlab-contrib/jupyterlab-favorites/pull/15

### CODE REVIEW

**Comment by fcollonval** [comment]
The releaser picked up the top repo correctly. But as a workspace listing the ui-test was present it tried to list all public packages part of the workspace requiring packaging. However in that specific case there is no public package in the workspace; hence the bug (it runs `npm pack` with no argument in a folder that is not a npm package) that this PR fixes.

**Comment by jtpio** [comment]
OK thanks for providing the extra context.

Maybe this case should be put under tests? Or we add a print / info statement if `workspaces` is defined but no packages will be published? In case there is a misconfiguration issue.

**Comment by fcollonval** [comment]
> we add a print / info statement if `workspaces` is defined but no packages will be published?

Thanks for the suggestion @jtpio; I added a log message in ee81639

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
