### PR TITLE
Run CI on Python 3.10

### PR DESCRIPTION
**Pull request by jtpio**
- Switch from Python `3.9` to `3.10` when testing on CI
- Update trove classifiers

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by blink1073** [comment]
Ah, this needs to be changed as well: https://github.com/jupyter-server/jupyter_releaser/blob/6b927843f50effa8c29f1a98b14f732b8dda1fef/docs/environment.yml#L5

**Comment by jtpio** [comment]
Thanks, done in https://github.com/jupyter-server/jupyter_releaser/pull/234/commits/df146c177260ec1b20e84ac8839ae3c979f1b943.

**Comment by blink1073** [comment]
Thanks!

**Pull request merged**
