### PR TITLE
add step N to actions to make it easier

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
Something else I was wondering about: in teh `since` field, does the user have to enter `v0.1.2`? Or would `0.1.2` also work? Because IIUC then in since we expect a `v` prefix, but in the version we expect it without a `v`?

**Comment by blink1073** [comment]
Since is looking for an actual tag, so whatever the tag is named.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by blink1073** [comment]
The `since` parameter is used by `github-activity`, which only operates on tags.  We could potentially check for the existence of a tag and add/remove the leading `v`. We do use the same language as `github-activity` for the [docs](        description: "Use PRs with activity since this date or git reference"): "date or git reference".

**Pull request merged**
