### PR TITLE
Pin `pypiserver` to v2.2.0

### PR DESCRIPTION
**Pull request by krassowski**
Fixes https://github.com/jupyter-server/jupyter_releaser/issues/595, workaround for https://github.com/pypiserver/pypiserver/issues/630.

Closes https://github.com/jupyter-server/jupyter_releaser/pull/594

### CODE REVIEW

**Review by brichet — APPROVED** [review]
Thanks @krassowski, LGTM

**Comment by brichet** [comment]
The tests that are failing are similar or I'm missing something ?
And none of them seem to be doing what they're supposed to, according to the names...

```yaml
  test_minimum_versions:
    name: Test Minimum Versions
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          dependency_type: pre
      - name: Run the unit tests
        run: |
          hatch run test:nowarn || hatch run test:nowarn --lf


  test_prereleases:
    name: Test Prereleases
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          dependency_type: pre
      - name: Run the tests
        run: |
          hatch run test:nowarn || hatch run test:nowarn --lf
```

**Comment by krassowski** [comment]
Good catch! I opened https://github.com/jupyter-server/jupyter_releaser/pull/597 to fix `test_minimum_versions`. Not sure what is wrong with `test_prereleases` though?

**Comment by brichet** [comment]
> Not sure what is wrong with `test_prereleases` though?

I through it was a test about releasing a version, you're right.

> Of course not great that these are timing out instead of failing.

We should probably skip it until it is fixed upstream.

**Comment by krassowski** [comment]
> We should probably skip it until it is fixed upstream.

Right, I commented it out of `check` job which is set as required. `test_prereleases` will keep failing but it will not block merging PRs in the meantime.

**Pull request merged**
